### ISSUE TITLE
"Cannot find module 'unocss-preset-autoprefixer'" when following installation instruction

### ISSUE THREAD

**Issue by awacode21** [unpreset/unocss-preset-autoprefixer#5]
I think the installation instruction might be wrong.

The instructions tell to install

`pnpm add lightningcss browserslist -D`

as i am using npm it would be

`npm install lightningcss browserslist --save-dev`

und use it like:
```
import presetUno from '@unocss/preset-uno'
import presetAutoprefixer from 'unocss-preset-autoprefixer'

Unocss({
  presets: [
    presetUno(),
    presetAutoprefixer()
  ],
})
```
But with that the build fails saying:
` [unhandledRejection] Cannot find module 'unocss-preset-autoprefixer'`

which is somehow logical as we never installed a package called unocss-preset-autoprefixer. Only lightningcss & browserslist packages got installed.

Shouldn't the install look like
`npm install unocss-preset-autoprefixer --save-dev`
instead?

Please adjust the instructions!

**Comment by zouhangwithsweet** [comment]
My fault. :)
