### ISSUE TITLE
With the unocss plugin prompt failure

### ISSUE THREAD

**Issue by chenxch** [unpreset/unocss-preset-autoprefixer#6]
unoconfig:
![image](https://github.com/zouhangwithsweet/unocss-preset-autoprefixer/assets/23251408/6d2f7a93-619e-4240-82ec-fc35cd7af53c)

unocss  output：
![image](https://github.com/zouhangwithsweet/unocss-preset-autoprefixer/assets/23251408/1e420197-4a45-4084-bd33-d00122977a5f)

When I commented unocss-preset-autoprefixer, all prompts returned to normal.

before:
![image](https://github.com/zouhangwithsweet/unocss-preset-autoprefixer/assets/23251408/671b3503-11ba-4956-bd74-339a8f4c5a59)

after:
![image](https://github.com/zouhangwithsweet/unocss-preset-autoprefixer/assets/23251408/6d288a14-a45e-4e00-ab65-f32fb9aba60c)

**Comment by chenxch** [comment]
Same problem with version 0.0.6.

**Comment by hestudy** [comment]
I have the same problem.

**Comment by liucaihe** [comment]
mee to

**Comment by zouhangwithsweet** [comment]
Can you generate correct css file at build ?
