### ISSUE TITLE
Maintain this package

### ISSUE THREAD

**Issue by zyyv** [unpreset/unocss-preset-autoprefixer#8]
@zouhangwithsweet I'd like to help maintain this package, including its updates and releases. Can you invite [me](https://www.npmjs.com/~zyyv) on [npm](https://www.npmjs.com/package/unocss-preset-autoprefixer)?

Background https://github.com/unocss/unocss/issues/4087

**Comment by zouhangwithsweet** [comment]
Just show me your npm account.

**Comment by zyyv** [comment]
same account: `zyyv`

**Comment by shuperry** [comment]
@zyyv Sorry to bother you, if this package is no longer maintained, is there any other way to implement autoprefixer functionality in unocss?

**Comment by zyyv** [comment]
> @zyyv Sorry to bother you, if this package is no longer maintained, is there any other way to implement autoprefixer functionality in unocss?

I think this is the best way. You can refer to this logic to process it in your project.
In addition, this package will continue to be maintained. Sorry for not updating it. I will look at the recent changelog and try to update the version.
